cameras:
  # - cam1:
  #     type: "ptz"
  #     task: "Anpr"
  #     source: 'rtsp://192.168.1.111'
  #     model_used: "ANPRModel"
  #     url: 'ws://192.168.1.111/cgi-bin/event-websock/streaming.cgi'
  #     base_url: 'http://192.168.1.111'

  # - cam2:
  #     type: "ptz_fixed"
  #     task: "Anpr"
  #     source: 'rtsp://192.168.1.111'
  #     model_used: "ANPRModel"
  #     url: 'ws://192.168.1.111/cgi-bin/event-websock/streaming.cgi'
  #     base_url: 'http://192.168.1.111'

  - cam3:
      type: "webcam"
      task: "Detection"
      source: 0
      model_used: "YOLOv11DetectionModel"
      


  - cam4:
      type: "video"
      task: "Detection"
      source: "/home/dhanjay/Desktop/Final_ANPR_UI_SupportingMultipleStreams/1900-151662242_small.mp4"
      model_used: "YOLOv11DetectionModel"

  - cam5:
      type: "webcam"
      task: "Detection"
      source: '/home/dhanjay/Desktop/Final_ANPR_UI_SupportingMultipleStreams/mov_bbb.mp4'
      model_used: "YOLOv11DetectionModel"
